### PR TITLE
Use an HttpListener for Authentication

### PR DESCRIPTION
**Pull request by AngelMunoz**
this addresses partially #53 
While I could start the workflow there are some issues yet
and since I can't add redirect URLs for the app for GOG I'm stuck at this
image
then
image

I'll send this as a draft PR if you want to continue the work based on this or let me know what else can I do for it

### CODE REVIEW

**Comment by NicoVIII** [comment]
Thanks for this!
Sad that the (not official to be fair) API of GOG doesn't allow this redirect. But the ideas in here look promising.
I will have a look at this and see what I can use to simplify the complicated authorization workflow!

**Comment by NicoVIII** [comment]
I implemented the opening of the browser you suggested, but i used a button for now. If the listening is not working, I guess it would be confusing, if the browser opens and after login the site stays simply white and it doesn't go on from there.
https://github.com/NicoVIII/Andromeda-for-GOG/commit/0364a4617658e3addac9e88428ca94d8200db8c4

I'm not sure for now if I want to get rid of the auth window, but the idea is growing on me 😄 
Once again thanks for your input!

**Comment by AngelMunoz** [comment]
> I'm not sure for now if I want to get rid of the auth window, but the idea is growing on me 😄

My opinion would be (you can completely ignore me in this 😁) that since the authentication part of the workflow of your app in one way or another thus making it part of the main window can I guess simplify some of that stuff since you can just show the "login" view if there's no authentication
putting the whole auth thing a window kind of throws me off, most of the apps I've seen they use the login screen as part of the main window and only do the pop up when you are accessing the third party website you are using as authentication and not before/after that

That's why on this draft branch I actually put the authentication in the state It felt easier for me checking for the presence of authentication and showing a specific view for that

**Comment by NicoVIII** [comment]
I removed the authentication window, I think this is nice and less confusing clutter.
At the start there were too many windows open at once, I guess it is easier if the user has only one thing to do at a time.
https://github.com/NicoVIII/Andromeda-for-GOG/commit/6fe137292bae2b5e58fd7f6aab1d9b124038e142

Are there any ideas of you open, which I didn't stole from you? 😄 Sorry btw. that I didn't accept your PR and implemented it by myself!

**Comment by AngelMunoz** [comment]
> Are there any ideas of you open, which I didn't stole from you? 😄 Sorry btw. that I didn't accept your PR and implemented it by myself!

It's fine no worries my PR isn't really doable the way I wanted due to the restrictions you mentioned, feel free to pick only the stuff you need 😁 

> Are there any ideas of you open, which I didn't stole from you? 

Such a harsh word 😆 I don't sell stuff so I don't think you can steal from me.

give me some time to think and reflect since I'll be busy these days 😁 but if anything comes to my mind I'll open an issue

**Pull request closed without merging**
