### PR TITLE
Move window out of state

### PR DESCRIPTION
**Pull request by AngelMunoz**
Addresses #51

### CODE REVIEW

**Comment by AngelMunoz** [comment]
There are other places like Dialog windows that have their own window like the `InstallGame` module where something similar could be done but that would require a further look and hence why I don't include them in this PR

**Comment by NicoVIII** [comment]
Thanks for this!

I will have a better look at it tomorrow and merge it then.
(First PR which is not mine, yay! :smile:)

**Comment by AngelMunoz** [comment]
No problem, let me know if anything comes out 😁

**Comment by NicoVIII** [comment]
I like it! I will try that.
I can imagine, that this simplifies the state and works for the subwindows and stuff as well.

Thank you! :)

**Pull request merged**
